/* Mayflower Studios — admin-only 3DX world library manager */
(function(){
  "use strict";
  const DB="https://watchtogether-95d7d-default-rtdb.firebaseio.com", FBVER="10.12.2";
  const $=id=>document.getElementById(id), esc=v=>String(v??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");
  if(!$('wmForm')) return;
  let user=null, token="", allowed=false, store=null, smod=null, items={}, editing=null;
  const msg=(text,bad=false)=>{const n=$('wmMsg');n.textContent=text||"";n.className="wmMsg "+(bad?"bad":"ok")};
  const progress=text=>{$('wmProgress').textContent=text||""};
  async function fresh(){if(!user)throw new Error("Not signed in");token=await user.getIdToken();return token}
  async function get(path, auth=true){const t=auth?`?auth=${encodeURIComponent(await fresh())}`:"";const r=await fetch(`${DB}/${path}.json${t}`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
  async function put(path,value){const r=await fetch(`${DB}/${path}.json?auth=${encodeURIComponent(await fresh())}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(value)});if(!r.ok)throw new Error(`HTTP ${r.status}: ${await r.text()}`);return r.json()}
  async function del(path){const r=await fetch(`${DB}/${path}.json?auth=${encodeURIComponent(await fresh())}`,{method:"DELETE"});if(!r.ok)throw new Error(`HTTP ${r.status}`)}
  async function check(u){
    user=u;if(!u)return;try{token=await fresh();const profile=window.MFAuth&&MFAuth.profile||{};let me=String(profile.username||"").toLowerCase();if(!me)me=String(await get(`users/${u.uid}/username`)||"").toLowerCase();if(!me)return;const [owner,admin]=await Promise.all([get("owner"),get(`admins/${encodeURIComponent(me)}`)]);allowed=String(owner||"").toLowerCase()===me||admin===true;if(!allowed)return;await initStorage();wire();load()}catch(e){console.warn("world manager gate",e);msg("World manager could not start: "+e.message,true)}}
  async function initStorage(){if(smod)return;smod=await import(`https://www.gstatic.com/firebasejs/${FBVER}/firebase-storage.js`);if(!MFAuth._app)throw new Error("Firebase app is not ready");store=smod.getStorage(MFAuth._app)}
  function wire(){if($('wmForm').dataset.wired)return;$('wmForm').dataset.wired="1";$('wmForm').addEventListener("submit",save);$('wmCancel').addEventListener("click",reset);$('wmRefresh').addEventListener("click",load);$('wmList').addEventListener("click",act)}
  function slug(s){return String(s||"").toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,60)||"world"}
  function safeName(s){return String(s||"file").replace(/[^a-zA-Z0-9._-]+/g,"-").slice(-100)}
  function fileOKWorld(f){return f&&/\.world$/i.test(f.name)&&f.size>0&&f.size<=250*1024*1024}
  function fileOKImage(f){return f&&/^image\/(jpeg|png|webp|gif)$/i.test(f.type)&&f.size>0&&f.size<=15*1024*1024}
  async function upload(file,path,contentType,onPct){const ref=smod.ref(store,path),task=smod.uploadBytesResumable(ref,file,{contentType:contentType||file.type||"application/octet-stream"});await new Promise((res,rej)=>task.on("state_changed",s=>{if(onPct)onPct(Math.round((s.bytesTransferred/s.totalBytes)*100))},rej,res));return {url:await smod.getDownloadURL(ref),path,name:file.name,size:file.size}}
  async function erase(path){if(!path)return;try{await smod.deleteObject(smod.ref(store,path))}catch(e){if(!String(e.code||"").includes("object-not-found"))console.warn("storage delete",path,e)}}
  async function load(){if(!allowed)return;$('wmList').innerHTML='<div class="acctEmpty">Loading…</div>';try{items=await get("worldLibrary",false)||{};draw()}catch(e){$('wmList').innerHTML=`<div class="acctEmpty">Could not load worlds: ${esc(e.message)}</div>`}}
  function draw(){const list=Object.entries(items).sort((a,b)=>((b[1]&&b[1].updatedAt)||0)-((a[1]&&a[1].updatedAt)||0));$('wmList').innerHTML=list.length?list.map(([id,w])=>`<div class="wmItem"><strong>${esc(w.title||id)}</strong><small>${w.published===false?"Hidden":"Public"}${w.featured?" · Featured":""} · ${(w.images&&Object.keys(w.images).length)||0} screenshot(s)</small><div class="wmItemBtns"><button type="button" data-edit="${esc(id)}">Edit</button><a class="btn ghost" style="font-size:11px;padding:5px 8px" href="/worlds.html?world=${encodeURIComponent(id)}" target="_blank" rel="noopener">View</a><button class="danger" type="button" data-delete="${esc(id)}">Delete</button></div></div>`).join(""):'<div class="acctEmpty">No worlds yet. Add the first one on the left.</div>'}
  function reset(){$('wmForm').reset();$('wmEditId').value="";$('wmCreator').value="Mayflower Studios";$('wmPublished').checked=true;$('wmSave').textContent="Publish world";$('wmCancel').hidden=true;$('wmCurrentWorld').textContent="Required for a new world. Leave empty while editing to keep the current file.";$('wmCurrentImages').textContent="Choose up to 20 images. The first one becomes the cover. Leave empty while editing to keep the current gallery.";editing=null;progress("");msg("")}
  function edit(id){const w=items[id];if(!w)return;editing=JSON.parse(JSON.stringify(w));$('wmEditId').value=id;$('wmTitle').value=w.title||"";$('wmCreator').value=w.creator||"Mayflower Studios";$('wmDescription').value=w.description||"";$('wmTags').value=(Array.isArray(w.tags)?w.tags:Object.values(w.tags||{})).join(", ");$('wmVersion').value=w.version||"";$('wmFeatured').checked=!!w.featured;$('wmPublished').checked=w.published!==false;$('wmSave').textContent="Save changes";$('wmCancel').hidden=false;$('wmCurrentWorld').textContent=`Current: ${(w.world&&w.world.name)||"world file"}. Choose a new .world only if you want to replace it.`;$('wmCurrentImages').textContent=`Current gallery: ${(w.images&&Object.keys(w.images).length)||0} screenshot(s). Choosing new images replaces the whole gallery.`;$('wmTitle').focus();$('world-library-admin').scrollIntoView({behavior:"smooth",block:"start"})}
  async function act(e){const ed=e.target.closest&&e.target.closest("[data-edit]"),de=e.target.closest&&e.target.closest("[data-delete]");if(ed){edit(ed.dataset.edit);return}if(!de)return;const id=de.dataset.delete,w=items[id];if(!w)return;if(!confirm(`Delete “${w.title||id}” and its uploaded files? This cannot be undone.`))return;try{progress("Deleting…");await initStorage();for(const im of (Array.isArray(w.images)?w.images:Object.values(w.images||{})))await erase(im&&im.path);await erase(w.world&&w.world.path);await del(`worldLibrary/${encodeURIComponent(id)}`);delete items[id];draw();if($('wmEditId').value===id)reset();msg("World deleted.");progress("")}catch(err){progress("");msg("Delete failed: "+err.message,true)}}
  async function save(e){e.preventDefault();if(!allowed)return;const title=$('wmTitle').value.trim(),description=$('wmDescription').value.trim(),creator=$('wmCreator').value.trim()||"Mayflower Studios",version=$('wmVersion').value.trim(),tags=$('wmTags').value.split(",").map(x=>x.trim()).filter(Boolean).slice(0,12);const wid=$('wmEditId').value||slug(title)+(items[slug(title)]&&!$('wmEditId').value?"-"+Date.now().toString(36):"");const wf=$('wmWorldFile').files[0], imageFiles=Array.from($('wmImages').files||[]);if(!title||!description){msg("Give the world a name and description first.",true);return}if(!editing&&!fileOKWorld(wf)){msg("Choose a .world file (up to 250 MB).",true);return}if(wf&&!fileOKWorld(wf)){msg("The world file must end in .world and be 250 MB or smaller.",true);return}if(imageFiles.length>20){msg("Choose no more than 20 screenshots.",true);return}if(imageFiles.some(f=>!fileOKImage(f))){msg("Screenshots must be JPG, PNG, WEBP or GIF and 15 MB or smaller each.",true);return}
    $('wmSave').disabled=true;try{await initStorage();const stamp=Date.now();let world=editing&&editing.world?editing.world:null,images=editing?(Array.isArray(editing.images)?editing.images:Object.values(editing.images||{})):[];let oldWorld=null,oldImages=[];
      if(wf){progress("Uploading world file…");const path=`world-library/${user.uid}/${wid}/world/${stamp}-${safeName(wf.name)}`;const nw=await upload(wf,path,"application/octet-stream",p=>progress(`Uploading world file… ${p}%`));oldWorld=world;world=nw}
      if(imageFiles.length){oldImages=images;images=[];for(let i=0;i<imageFiles.length;i++){const f=imageFiles[i],path=`world-library/${user.uid}/${wid}/images/${stamp}-${i+1}-${safeName(f.name)}`;progress(`Uploading screenshot ${i+1} of ${imageFiles.length}…`);images.push(await upload(f,path,f.type,p=>progress(`Screenshot ${i+1}/${imageFiles.length}… ${p}%`)))} }
      const now=Date.now(),record={title,creator,description,tags,version,featured:$('wmFeatured').checked,published:$('wmPublished').checked,world,images,createdAt:editing&&editing.createdAt||now,updatedAt:now,createdByUid:editing&&editing.createdByUid||user.uid,createdByName:editing&&editing.createdByName||(MFAuth.name&&MFAuth.name())||creator};
      progress("Publishing…");await put(`worldLibrary/${encodeURIComponent(wid)}`,record);if(oldWorld&&oldWorld.path&&oldWorld.path!==world.path)await erase(oldWorld.path);if(oldImages.length)for(const im of oldImages)if(im&&im.path&&!images.some(x=>x.path===im.path))await erase(im.path);items[wid]=record;draw();reset();msg(`“${title}” is live in the World Library.`)}catch(err){console.warn("world publish",err);msg("Publish failed: "+err.message,true);progress("")}finally{$('wmSave').disabled=false}}
  function wait(){if(!window.MFAuth){setTimeout(wait,100);return}MFAuth.onChange((u)=>check(u))}wait();
})();
