/* Mayflower Studios — scheduled site announcement banner */
(function(){
  const FB='10.12.2';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  let db=null,mods=null,user=null,profile=null,role='guest',announcements={},dismissals={},unsubA=null,unsubD=null;
  const $=id=>document.getElementById(id);
  function injectStyles(){if($('mfAnnouncementStyles'))return;const s=document.createElement('style');s.id='mfAnnouncementStyles';s.textContent=`
    .mf-announcements{position:relative;z-index:45;display:grid;gap:7px;width:min(1120px,calc(100% - 32px));margin:10px auto 0}.mf-announcement{--ann-accent:var(--violet);display:grid;grid-template-columns:auto minmax(0,1fr) auto;gap:11px;align-items:center;padding:11px 13px;border:1px solid color-mix(in srgb,var(--ann-accent),transparent 66%);border-radius:14px;background:color-mix(in srgb,var(--ann-accent),rgba(12,18,32,.96) 90%);box-shadow:0 12px 34px rgba(0,0,0,.18)}
    .mf-announcement.celebrate{--ann-accent:var(--rose)}.mf-announcement.warning{--ann-accent:#fbbf24}.mf-announcement.urgent{--ann-accent:#fb7185}.mf-ann-icon{font-size:19px}.mf-ann-copy{min-width:0}.mf-ann-title{display:block;font-size:12.8px}.mf-ann-body{display:block;margin-top:2px;color:var(--text-2);font-size:11.8px;line-height:1.45}.mf-ann-actions{display:flex;align-items:center;gap:7px}.mf-ann-actions a,.mf-ann-actions button{font:inherit;font-size:11px;border:1px solid rgba(255,255,255,.12);border-radius:999px;padding:5px 9px;color:var(--text-2);background:rgba(0,0,0,.16);text-decoration:none;cursor:pointer}.mf-ann-actions a:hover,.mf-ann-actions button:hover{color:var(--text);border-color:var(--ann-accent)}
    @media(max-width:640px){.mf-announcements{width:min(100% - 16px,1120px);margin-top:7px}.mf-announcement{grid-template-columns:auto 1fr}.mf-ann-actions{grid-column:2;justify-content:flex-start;flex-wrap:wrap}}
  `;document.head.appendChild(s);}
  function container(){let c=$('mfAnnouncements');if(c)return c;c=document.createElement('div');c.id='mfAnnouncements';c.className='mf-announcements';c.setAttribute('data-no-translate','');const nav=$('site-nav')||$('shared-nav');if(nav&&nav.parentNode)nav.insertAdjacentElement('afterend',c);else document.body.prepend(c);return c;}
  function localDismissed(id){try{return localStorage.getItem('mf_announcement_dismissed_'+id)==='1';}catch(_){return false;}}
  function audienceOkay(a){const audience=String(a.audience||'everyone');if(audience==='everyone')return true;if(!user)return false;if(audience==='signed_in')return true;if(audience==='owner')return role==='owner';if(audience==='admins')return role==='owner'||role==='admin';if(audience==='users')return role==='user';return false;}
  function active(a){const now=Date.now(),start=Number(a.startAt)||0,end=Number(a.endAt)||0;return(!start||start<=now)&&(!end||end>now)&&audienceOkay(a);}
  function iconFor(style){return style==='urgent'?'🚨':style==='warning'?'⚠️':style==='celebrate'?'🌸':'📣';}
  function draw(){const c=container();const rows=Object.entries(announcements||{}).map(([id,v])=>({id,...(v||{})})).filter(a=>active(a)&&!(user?(dismissals&&dismissals[a.id]):localDismissed(a.id))).sort((a,b)=>{const p={urgent:0,warning:1,celebrate:2,info:3};return(p[a.style]??3)-(p[b.style]??3)||(Number(b.startAt)||0)-(Number(a.startAt)||0);}).slice(0,4);c.hidden=!rows.length;c.innerHTML=rows.map(a=>`<article class="mf-announcement ${esc(a.style||'info')}" data-ann-id="${esc(a.id)}"><span class="mf-ann-icon">${iconFor(a.style)}</span><span class="mf-ann-copy"><b class="mf-ann-title">${esc(a.title||'Announcement')}</b><span class="mf-ann-body">${esc(a.body||'')}</span></span><span class="mf-ann-actions">${a.link&&String(a.link).startsWith('/')?`<a href="${esc(a.link)}">Learn more</a>`:''}${a.dismissible!==false?`<button type="button" data-ann-dismiss="${esc(a.id)}">Dismiss</button>`:''}</span></article>`).join('');c.querySelectorAll('[data-ann-dismiss]').forEach(b=>b.addEventListener('click',()=>dismiss(b.dataset.annDismiss)));}
  async function dismiss(id){if(!id)return;if(user&&mods){dismissals={...(dismissals||{}),[id]:Date.now()};draw();try{await mods.set(mods.ref(db,`announcementDismissals/${user.uid}/${id}`),Date.now());}catch(_){}}else{try{localStorage.setItem('mf_announcement_dismissed_'+id,'1');}catch(_){}draw();}}
  async function determineRole(){role=user?'user':'guest';if(!user||!mods)return;const handle=String((profile&&profile.username)||'').trim().toLowerCase();if(!handle)return;try{const [o,a]=await Promise.all([mods.get(mods.ref(db,'owner')),mods.get(mods.ref(db,`admins/${handle}`))]);if(o.exists()&&String(o.val()||'').toLowerCase()===handle)role='owner';else if(a.val()===true)role='admin';}catch(_){} }
  function watchDismissals(){if(unsubD){try{unsubD();}catch(_){}unsubD=null;}dismissals={};if(!user||!mods){draw();return;}const r=mods.ref(db,`announcementDismissals/${user.uid}`),cb=s=>{dismissals=s.exists()?(s.val()||{}):{};draw();};mods.onValue(r,cb,()=>{dismissals={};draw();});unsubD=()=>mods.off(r,'value',cb);}
  async function authChanged(u,p){user=u||null;profile=p||null;if(!db){db=MFAuth.db;if(!db)return setTimeout(()=>authChanged(MFAuth.user,MFAuth.profile),100);}if(!mods)mods=await import(`https://www.gstatic.com/firebasejs/${FB}/firebase-database.js`);await determineRole();watchDismissals();draw();}
  async function boot(){injectStyles();container();const wait=async()=>{if(!window.MFAuth||!MFAuth.onChange)return setTimeout(wait,100);db=MFAuth.db;if(!db)return setTimeout(wait,100);if(!mods)mods=await import(`https://www.gstatic.com/firebasejs/${FB}/firebase-database.js`);const r=mods.ref(db,'siteAnnouncements'),cb=s=>{announcements=s.exists()?(s.val()||{}):{};draw();};mods.onValue(r,cb,()=>{announcements={};draw();});unsubA=()=>mods.off(r,'value',cb);MFAuth.onChange(authChanged);setInterval(draw,60000);};wait();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
})();
