/* somewhere between — glossary.pt.js */
var GLOSSARY={
  splitting:{title:"divisão (TPB)",body:"Uma característica central da TPB em que a pessoa vê os outros como completamente bons ou completamente maus — sem meio-termo. Uma amiga próxima pode passar de uma âncora emocional a uma ameaça — frequentemente sem gatilho claro e sem aviso."},
  fp:{title:"pessoa favorita (TPB)",body:"Na TPB, uma PF é alguém com quem a pessoa forma um vínculo intenso. O humor, as palavras e a disponibilidade da PF parecem controlar completamente o estado emocional da pessoa. Isso pode ser exaustivo para os dois envolvidos."},
  abandonment:{title:"medo de abandono (TPB)",body:"Um medo generalizado, muitas vezes avassalador, de que as pessoas vão embora — mesmo quando não há evidência real disso. Pode causar comportamentos de verificação, busca excessiva de reasseguração ou retirada preventiva para evitar ser deixada primeiro."},
  reassurance:{title:"busca de reasseguração (TPB/ansiedade)",body:"Pedir repetidamente confirmação de que tudo está bem. Oferece alívio temporário, mas reforça a ansiedade a longo prazo — o alívio nunca dura totalmente, o checar continua e o ciclo se aperta."},
  dpd:{title:"transtorno de personalidade dependente",body:"O TPD envolve uma necessidade generalizada de que outros assumam a responsabilidade por decisões, forneçam orientação ou validem ações. Mesmo pequenas decisões podem parecer impossíveis sem input externo, e dizer 'não' pode parecer genuinamente aterrorizante."},
  executive:{title:"disfunção executiva",body:"Um sintoma da depressão (e outras condições) que torna difícil iniciar, planejar ou concluir tarefas — mesmo as simples. Frequentemente parece paralisia ou estar 'travada'. Não é uma falha de caráter."},
  hypervigilance:{title:"hipervigilância (ansiedade/TPB)",body:"Um estado de alerta elevado a ameaças potenciais — escanear expressões faciais, tom de voz e timing de mensagens em busca de sinais de raiva ou rejeição. Exaustivo e constante, mesmo em situações objetivamente seguras."},
  intrusive:{title:"dúvida intrusiva (ansiedade/TOC-adjacente)",body:"Pensamentos indesejados que aparecem sem aviso — frequentemente sobre piores cenários ou comportamentos de verificação (apaguei o fogão?). Quanto mais você tenta não pensá-los, mais insistentes eles se tornam."},
  anhedonia:{title:"anedonia (depressão)",body:"A perda de interesse ou prazer em atividades que costumavam ser significativas. Não exatamente tristeza — mais uma planura, uma ausência, que é muito difícil de descrever para alguém que não a vivenciou."},
  masking:{title:"mascaramento",body:"Esconder ou suprimir sintomas e sofrimento interno para parecer funcional. Funciona a curto prazo e custa muito a longo prazo. Pessoas que mascaram bem frequentemente ouvem que 'não parecem deprimidas', o que agrava o isolamento."},
  emotional_intensity:{title:"intensidade emocional (TPB)",body:"As emoções na TPB são frequentemente vivenciadas com muito mais intensidade do que em pessoas neurotípicas e mudam rapidamente. O que parece uma reação exagerada por fora pode parecer, por dentro, a única resposta proporcional a algo genuinamente insuportável."},
  dissociation:{title:"dissociação",body:"Uma desconexão dos seus pensamentos, sentimentos ou ambiente — variando de leve distanciamento a sentir que você está se observando de fora do seu corpo. Frequentemente desencadeada por estresse ou sobrecarga emocional como resposta protetora."},
  object_constancy:{title:"constância objetal (TPB)",body:"A capacidade de manter um senso estável de alguém — de lembrar que você a ama e ela a ama — quando está ausente, fria ou frustrante. A TPB frequentemente perturba isso. Quando Maya fica em silêncio, pode parecer que a versão calorosa dela simplesmente deixa de existir."}
};
