/* somewhere between — glossary.de.js */
var GLOSSARY={
  splitting:{title:"Splitting (BPS)",body:"Ein Kernmerkmal der BPS, bei dem eine Person andere entweder als vollständig gut oder vollständig schlecht betrachtet — ohne Mittelweg. Ein enger Freund kann sich von einer Lebensader zu einer Bedrohung wandeln — oft ohne erkennbaren Auslöser und ohne Vorwarnung."},
  fp:{title:"Lieblingsperson (BPS)",body:"Bei der BPS ist eine LP jemand, an den sich die Person intensiv gebunden fühlt. Die Stimmung, die Worte und die Verfügbarkeit der LP fühlen sich an, als würden sie den emotionalen Zustand der Person vollständig kontrollieren. Das kann für beide Beteiligten erschöpfend sein."},
  abandonment:{title:"Verlustangst (BPS)",body:"Eine allgegenwärtige, oft überwältigende Angst davor, dass Menschen gehen werden — auch wenn es dafür keine wirklichen Hinweise gibt. Sie kann zu Kontrollverhalten, übermäßiger Bestätigungssuche oder vorweggenommenem Rückzug führen, um dem Verlassenwerden zuvorzukommen."},
  reassurance:{title:"Bestätigungssuche (BPS/Angst)",body:"Das wiederholte Nachfragen nach Bestätigung, dass alles in Ordnung ist. Es bietet vorübergehende Erleichterung, verstärkt aber langfristig die Angst — die Erleichterung hält nie vollständig an, das Kontrollieren geht weiter und der Kreislauf wird enger."},
  dpd:{title:"Abhängige Persönlichkeitsstörung",body:"APS beinhaltet ein durchgehendes Bedürfnis, dass andere die Verantwortung für Entscheidungen übernehmen, Orientierung geben oder Handlungen bestätigen. Selbst kleine Entscheidungen können sich ohne externen Input unmöglich anfühlen, und Nein zu sagen kann sich wirklich beängstigend anfühlen."},
  executive:{title:"Exekutive Dysfunktion",body:"Ein Symptom der Depression (und anderer Erkrankungen), das es schwer macht, Aufgaben zu beginnen, zu planen oder abzuschließen — selbst einfache. Es fühlt sich oft wie Lähmung oder Steckenbleiben an. Es ist kein Charakterfehler."},
  hypervigilance:{title:"Hypervigilanz (Angst/BPS)",body:"Ein Zustand erhöhter Wachsamkeit gegenüber potenziellen Bedrohungen — das Scannen von Gesichtsausdrücken, Tonfall und Timing von Nachrichten auf Anzeichen von Ärger oder Ablehnung. Erschöpfend und konstant, selbst in objektiv sicheren Situationen."},
  intrusive:{title:"Aufdringliche Zweifel (Angst/OCD-angrenzend)",body:"Unerwünschte Gedanken, die ohne Vorwarnung auftauchen — oft über Worst-Case-Szenarien oder Kontrollverhalten (habe ich den Herd ausgemacht?). Je mehr man versucht, sie nicht zu denken, desto hartnäckiger werden sie."},
  anhedonia:{title:"Anhedonie (Depression)",body:"Der Verlust des Interesses oder der Freude an Aktivitäten, die früher bedeutungsvoll wirkten. Nicht genau Traurigkeit — eher eine Flachheit, ein Fehlen, das sehr schwer zu beschreiben ist für jemanden, der es nicht erlebt hat."},
  masking:{title:"Masking",body:"Das Verstecken oder Unterdrücken von Symptomen und innerem Leid, um funktionsfähig zu erscheinen. Es funktioniert kurzfristig und kostet langfristig viel. Menschen, die gut maskieren, wird oft gesagt, dass sie 'nicht depressiv wirken', was die Isolation verstärkt."},
  emotional_intensity:{title:"Emotionale Intensität (BPS)",body:"Emotionen werden bei BPS oft mit viel höherer Intensität erlebt als bei neurotypischen Menschen und wechseln schnell. Was von außen wie eine Überreaktion aussieht, kann sich von innen wie die einzige angemessene Reaktion auf etwas wirklich Unerträgliches anfühlen."},
  dissociation:{title:"Dissoziation",body:"Eine Abkopplung von den eigenen Gedanken, Gefühlen oder der Umgebung — von leichtem Abschalten bis hin zum Gefühl, sich selbst von außen zuzuschauen. Oft durch Stress oder emotionale Überwältigung als Schutzreaktion ausgelöst."},
  object_constancy:{title:"Objektkonstanz (BPS)",body:"Die Fähigkeit, ein stabiles Bild von jemandem aufrechtzuerhalten — sich daran zu erinnern, dass man sie liebt und sie einen lieben — auch wenn sie abwesend, kühl oder frustrierend sind. BPS stört dies häufig. Wenn Maya still wird, kann es sich anfühlen, als würde die warme Version von ihr aufhören zu existieren."}
};
